/// Build and parse pairing URLs in the format:
/// `privet://pair?h=IP:PORT&h=IP2:PORT&fp=FULL_FINGERPRINT&n=NAME&code=123456`
///
/// "h" (host) is used instead of "addr" to keep the URL compact for QR codes.
/// Hosts are informational: pairing itself is keyed by the **full** fingerprint
/// (the daemon's `pair` matches a discovered peer's fingerprint exactly), so
/// the fingerprint is never truncated here.
class PairingUrl {
  /// Build a pairing URL from the device identity, optional hosts and an
  /// optional pairing code (generated by `generate_pairing_code`).
  static String build({
    required String fingerprint,
    required String deviceName,
    List<String> hosts = const [],
    String? code,
  }) {
    final params = <String>[
      for (final h in hosts) 'h=${Uri.encodeComponent(h)}',
      'fp=${Uri.encodeComponent(fingerprint)}',
      'n=${Uri.encodeComponent(deviceName)}',
      if (code != null && code.isNotEmpty) 'code=${Uri.encodeComponent(code)}',
    ];
    return 'privet://pair?${params.join('&')}';
  }

  /// Parse a `privet://pair?...` URL into its components.
  /// Returns null if the URL is not a valid pairing URL (missing fingerprint).
  static ParsedPairingUrl? parse(String url) {
    final uri = Uri.tryParse(url);
    if (uri == null || uri.scheme != 'privet' || uri.host != 'pair') {
      return null;
    }

    final hosts = <String>[];
    for (final entry in uri.queryParametersAll.entries) {
      if (entry.key == 'h') hosts.addAll(entry.value);
    }

    final fingerprint = uri.queryParameters['fp'] ?? '';
    if (fingerprint.isEmpty) return null;

    return ParsedPairingUrl(
      hosts: hosts,
      fingerprint: fingerprint,
      deviceName: uri.queryParameters['n'] ?? '',
      code: uri.queryParameters['code'],
    );
  }
}

class ParsedPairingUrl {
  final List<String> hosts; // "IP:PORT" strings
  final String fingerprint;
  final String deviceName;
  final String? code;

  const ParsedPairingUrl({
    required this.hosts,
    required this.fingerprint,
    required this.deviceName,
    this.code,
  });

  @override
  String toString() =>
      'ParsedPairingUrl(hosts=$hosts, fingerprint=$fingerprint, name=$deviceName, code=$code)';
}
